export class Planning {
  id : number ;
  monday : boolean ;
  mondayOpen : string ;
  mondayClose : string ;
  tuesday : boolean ;
  tuesdayOpen : string ;
  tuesdayClose : string ;
  wednesday : boolean ;
  wednesdayOpen : string ;
  wednesdayClose : string ;
  thursday : boolean ;
  thursdayOpen : string ;
  thursdayClose : string ;
  friday : boolean ;
  fridayOpen : string ;
  fridayClose : string ;
  saturday : boolean ;
  saturdayOpen : string ;
  saturdayClose : string ;
  sunday : boolean ;
  sundayOpen : string ;
  sundayClose : string ;
}
